// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/tracking
package main

import (
	"context"
	"fmt"

	parcelevents "github.com/sdk-fixture-lab-260904/parcel-events-go"
)

func main() {
	ctx := context.Background()
	client := parcelevents.NewClient(parcelevents.WithAPIKey("my-api-key"))
	result, err := client.Tracking.Retrieve(ctx, "PE-000000000000")
	if err != nil {
		panic(err)
	}
	fmt.Println(result)
}
