// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"encoding/json"
	"fmt"
	"net/url"
)

// decodeResponse decodes a parsed JSON body into T via a JSON round trip.
func decodeResponse[T any](data any) (T, error) {
	var out T
	raw, err := json.Marshal(data)
	if err != nil {
		return out, fmt.Errorf("encode response: %w", err)
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return out, fmt.Errorf("decode response: %w", err)
	}
	return out, nil
}

// pathParam percent-encodes one path parameter value.
func pathParam(value any) string {
	return url.PathEscape(fmt.Sprint(value))
}

// queryJSON reduces a typed value to plain JSON data (nil on failure —
// a nil query value is skipped by the kernel).
func queryJSON(value any) any {
	raw, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	var out any
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil
	}
	return out
}
