// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Package parcelevents is the github.com/sdk-fixture-lab-260904/parcel-events-go SDK, generated by the
// Doctorine SDK Foundry (sdkSha 6f258615ff15). Runtime dependencies:
// the Go standard library only — the HTTP kernel is vendored under kernel/.
package parcelevents
