// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-go/kernel"
)

// ShipmentsService is the `shipments` resource.
type ShipmentsService struct {
	core *core

	Events *ShipmentsEventsService
}

func newShipmentsService(c *core) *ShipmentsService {
	s := &ShipmentsService{core: c}
	s.Events = newShipmentsEventsService(c)
	return s
}

// Cancel — Cancel a shipment before handoff
//
// `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
func (s *ShipmentsService) Cancel(ctx context.Context, shipmentID string, opts ...kernel.RequestOption) error {
	_, err := s.core.do(ctx, "DELETE", "/v1/shipments/"+pathParam(shipmentID), opts...)
	if err != nil {
		return err
	}
	return nil
}

// Create — Create a shipment
//
// `POST /v1/shipments` (`createShipment`)
func (s *ShipmentsService) Create(ctx context.Context, body CreateShipmentRequest, params ShipmentsCreateParams, opts ...kernel.RequestOption) (*Shipment, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithHeader("idempotency-key", params.IdempotencyKey))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/shipments", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List — List shipments
//
// `GET /v1/shipments` (`listShipments`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *ShipmentsService) List(ctx context.Context, params ShipmentsListParams) (*kernel.Page[Shipment], error) {
	query := make([]kernel.QueryParam, 0, 3)
	if params.Cursor != nil {
		query = append(query, kernel.QueryParam{Name: "cursor", Value: *params.Cursor})
	}
	if params.Limit != nil {
		query = append(query, kernel.QueryParam{Name: "limit", Value: *params.Limit})
	}
	query = append(query, kernel.QueryParam{Name: "status", Value: queryJSON(params.Status)})
	request := kernel.PageRequest{Method: "GET", URL: "/v1/shipments", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[Shipment](ctx, s.core, request, scheme)
}

// Retrieve — Retrieve a shipment
//
// `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
func (s *ShipmentsService) Retrieve(ctx context.Context, shipmentID string, opts ...kernel.RequestOption) (*Shipment, error) {
	response, err := s.core.do(ctx, "GET", "/v1/shipments/"+pathParam(shipmentID), opts...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — Update delivery instructions
//
// `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
func (s *ShipmentsService) Update(ctx context.Context, shipmentID string, body UpdateShipmentRequest, opts ...kernel.RequestOption) (*Shipment, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "PATCH", "/v1/shipments/"+pathParam(shipmentID), options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ShipmentsCreateParams holds the query/header parameters of `shipments.create`.
type ShipmentsCreateParams struct {
	IdempotencyKey string
}

// ShipmentsListParams holds the query/header parameters of `shipments.list`.
type ShipmentsListParams struct {
	Cursor *string

	Limit *int64

	Status *ShipmentStatus
}
