// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-go/kernel"
)

// PickupsService is the `pickups` resource.
type PickupsService struct {
	core *core
}

func newPickupsService(c *core) *PickupsService {
	s := &PickupsService{core: c}
	return s
}

// Cancel — Cancel a pickup
//
// `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
func (s *PickupsService) Cancel(ctx context.Context, pickupID string, opts ...kernel.RequestOption) error {
	_, err := s.core.do(ctx, "DELETE", "/v1/pickups/"+pathParam(pickupID), opts...)
	if err != nil {
		return err
	}
	return nil
}

// Create — Schedule a carrier pickup
//
// `POST /v1/pickups` (`createPickup`)
func (s *PickupsService) Create(ctx context.Context, body CreatePickupRequest, params PickupsCreateParams, opts ...kernel.RequestOption) (*Pickup, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithHeader("idempotency-key", params.IdempotencyKey))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/pickups", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Pickup](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List — List scheduled pickups
//
// `GET /v1/pickups` (`listPickups`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *PickupsService) List(ctx context.Context, params PickupsListParams) (*kernel.Page[Pickup], error) {
	query := make([]kernel.QueryParam, 0, 3)
	if params.Cursor != nil {
		query = append(query, kernel.QueryParam{Name: "cursor", Value: *params.Cursor})
	}
	if params.Limit != nil {
		query = append(query, kernel.QueryParam{Name: "limit", Value: *params.Limit})
	}
	if params.ScheduledOn != nil {
		query = append(query, kernel.QueryParam{Name: "scheduled_on", Value: *params.ScheduledOn})
	}
	request := kernel.PageRequest{Method: "GET", URL: "/v1/pickups", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[Pickup](ctx, s.core, request, scheme)
}

// Retrieve — Retrieve a pickup
//
// `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
func (s *PickupsService) Retrieve(ctx context.Context, pickupID string, opts ...kernel.RequestOption) (*Pickup, error) {
	response, err := s.core.do(ctx, "GET", "/v1/pickups/"+pathParam(pickupID), opts...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Pickup](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PickupsCreateParams holds the query/header parameters of `pickups.create`.
type PickupsCreateParams struct {
	IdempotencyKey string
}

// PickupsListParams holds the query/header parameters of `pickups.list`.
type PickupsListParams struct {
	Cursor *string

	Limit *int64

	ScheduledOn *string
}
