// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-go/kernel"
)

// LabelsService is the `labels` resource.
type LabelsService struct {
	core *core
}

func newLabelsService(c *core) *LabelsService {
	s := &LabelsService{core: c}
	return s
}

// Create — Buy and render a shipping label
//
// `POST /v1/labels` (`createLabel`)
func (s *LabelsService) Create(ctx context.Context, body CreateLabelRequest, params LabelsCreateParams, opts ...kernel.RequestOption) (*Label, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithHeader("idempotency-key", params.IdempotencyKey))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/labels", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Label](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve — Retrieve label metadata and download URL
//
// `GET /v1/labels/{label_id}` (`retrieveLabel`)
func (s *LabelsService) Retrieve(ctx context.Context, labelID string, opts ...kernel.RequestOption) (*Label, error) {
	response, err := s.core.do(ctx, "GET", "/v1/labels/"+pathParam(labelID), opts...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Label](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LabelsCreateParams holds the query/header parameters of `labels.create`.
type LabelsCreateParams struct {
	IdempotencyKey string
}
