// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-go/kernel"
)

// TrackingService is the `tracking` resource.
type TrackingService struct {
	core *core
}

func newTrackingService(c *core) *TrackingService {
	s := &TrackingService{core: c}
	return s
}

// Retrieve — Retrieve a public tracking timeline
//
// `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
func (s *TrackingService) Retrieve(ctx context.Context, trackingNumber string, opts ...kernel.RequestOption) (*TrackingTimeline, error) {
	response, err := s.core.do(ctx, "GET", "/v1/tracking/"+pathParam(trackingNumber), opts...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[TrackingTimeline](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
