// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parcelevents

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-go/kernel"
)

// ShipmentsEventsService is the `shipments.events` resource.
type ShipmentsEventsService struct {
	core *core
}

func newShipmentsEventsService(c *core) *ShipmentsEventsService {
	s := &ShipmentsEventsService{core: c}
	return s
}

// List — List tracking events for a shipment
//
// `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *ShipmentsEventsService) List(ctx context.Context, shipmentID string, params ShipmentsEventsListParams) (*kernel.Page[TrackingEvent], error) {
	query := make([]kernel.QueryParam, 0, 2)
	if params.Cursor != nil {
		query = append(query, kernel.QueryParam{Name: "cursor", Value: *params.Cursor})
	}
	if params.Limit != nil {
		query = append(query, kernel.QueryParam{Name: "limit", Value: *params.Limit})
	}
	request := kernel.PageRequest{Method: "GET", URL: "/v1/shipments/" + pathParam(shipmentID) + "/events", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[TrackingEvent](ctx, s.core, request, scheme)
}

// ShipmentsEventsListParams holds the query/header parameters of `shipments.events.list`.
type ShipmentsEventsListParams struct {
	Cursor *string

	Limit *int64
}
