// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/pickups
package main

import (
	"context"
	"fmt"

	parcelevents "github.com/sdk-fixture-lab-260904/parcel-events-go"
)

func main() {
	ctx := context.Background()
	client := parcelevents.NewClient(parcelevents.WithAPIKey("my-api-key"))
	if err := client.Pickups.Cancel(ctx, "pku_00000000000000000000"); err != nil {
		panic(err)
	}
	fmt.Println("ok")
}
